package pl.pcz.wimii.zpi.smartplan.entities;
// Generated 2015-12-07 21:04:58 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Godziny generated by hbm2java
 */
@Entity
//@XmlRootElement(name = "godziny")
@Table(name = "godziny", catalog = "smartplan"
)
public class Godziny implements java.io.Serializable {

    private Integer id;
    private String godz;
    private Set<Zajecia> zajecias = new HashSet<>(0);

    public Godziny() {
    }

    public Godziny(String godz) {
        this.godz = godz;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "godz", length = 10)
    public String getGodz() {
        return this.godz;
    }

    public void setGodz(String godz) {
        this.godz = godz;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "godziny")
    public Set<Zajecia> getZajecias() {
        return this.zajecias;
    }

    public void setZajecias(Set<Zajecia> zajecias) {
        this.zajecias = zajecias;
    }

}
