package pl.pcz.wimii.zpi.smartplan.entities;
// Generated 2015-12-07 21:04:58 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Godziny generated by hbm2java
 */
@Entity
//@XmlRootElement(name = "godziny")
@Table(name = "godziny", catalog = "smartplan_db"
)
public class Godziny implements java.io.Serializable, Comparable<Godziny> {

    private Integer id;
    private String godz;

    public Godziny() {
    }

    public Godziny(String godz) {
        this.godz = godz;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "godz", length = 10)
    public String getGodz() {
        return this.godz;
    }

    public void setGodz(String godz) {
        this.godz = godz;
    }

    @Override
    public String toString() {
        return "Godziny{" + "id=" + id + ", godz=" + godz + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.godz);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Godziny other = (Godziny) obj;
        if (!Objects.equals(this.godz, other.godz)) {
            return false;
        }
        return true;
    }

    @Override
    public int compareTo(Godziny o) {
        return this.getId().compareTo(o.getId());
    }

}
