package pl.pcz.wimii.zpi.smartplan.entities;
// Generated 2015-12-07 21:04:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plany generated by hbm2java
 */
@Entity
@Table(name="plany"
    ,catalog="smartplan"
)
public class Plany  implements java.io.Serializable {


     private Integer id;
     private RokKierunek rokKierunek;
     private String planNazw;
     private Date dataPublikacji;
     private Date dataDodania;
     private int widoczny;
     private Integer rok;
     private String kierunek;
     private Set<Zajecia> zajecias = new HashSet<>(0);

    public Plany() {
    }

	
    public Plany(RokKierunek rokKierunek, int widoczny) {
        this.rokKierunek = rokKierunek;
        this.widoczny = widoczny;
    }
    public Plany(RokKierunek rokKierunek, String planNazw, Date dataPublikacji, Date dataDodania, int widoczny, Integer rok, String kierunek, Set<Zajecia> zajecias) {
       this.rokKierunek = rokKierunek;
       this.planNazw = planNazw;
       this.dataPublikacji = dataPublikacji;
       this.dataDodania = dataDodania;
       this.widoczny = widoczny;
       this.rok = rok;
       this.kierunek = kierunek;
       this.zajecias = zajecias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rok_kierunek_id", nullable=false)
    public RokKierunek getRokKierunek() {
        return this.rokKierunek;
    }
    
    public void setRokKierunek(RokKierunek rokKierunek) {
        this.rokKierunek = rokKierunek;
    }

    
    @Column(name="plan_nazw", length=45)
    public String getPlanNazw() {
        return this.planNazw;
    }
    
    public void setPlanNazw(String planNazw) {
        this.planNazw = planNazw;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_publikacji", length=10)
    public Date getDataPublikacji() {
        return this.dataPublikacji;
    }
    
    public void setDataPublikacji(Date dataPublikacji) {
        this.dataPublikacji = dataPublikacji;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_dodania", length=10)
    public Date getDataDodania() {
        return this.dataDodania;
    }
    
    public void setDataDodania(Date dataDodania) {
        this.dataDodania = dataDodania;
    }

    
    @Column(name="widoczny", nullable=false)
    public int getWidoczny() {
        return this.widoczny;
    }
    
    public void setWidoczny(int widoczny) {
        this.widoczny = widoczny;
    }

    
    @Column(name="rok")
    public Integer getRok() {
        return this.rok;
    }
    
    public void setRok(Integer rok) {
        this.rok = rok;
    }

    
    @Column(name="kierunek", length=45)
    public String getKierunek() {
        return this.kierunek;
    }
    
    public void setKierunek(String kierunek) {
        this.kierunek = kierunek;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plany")
    public Set<Zajecia> getZajecias() {
        return this.zajecias;
    }
    
    public void setZajecias(Set<Zajecia> zajecias) {
        this.zajecias = zajecias;
    }




}


