package pl.pcz.wimii.zpi.smartplan.entities;
// Generated 2015-12-07 21:04:58 by Hibernate Tools 4.3.1


import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Przedmioty generated by hbm2java
 */
@Entity
@Table(name="przedmioty"
    ,catalog="smartplan"
)
public class Przedmioty  implements java.io.Serializable {


     private Integer id;
     private String nazwa;
     private Plany plan;

    public Przedmioty() {
    }

	
    public Przedmioty( String nazwa) {
        this.nazwa = nazwa;
    }
    public Przedmioty( String nazwa, Set<Zajecia> zajecias) {
       this.nazwa = nazwa;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="nazwa", nullable=false, length=45)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "plany_id")
    public Plany getPlan() {
        return plan;
    }

    public void setPlan(Plany plan) {
        this.plan = plan;
    }


    @Override
    public String toString() {
        return "Przedmioty{" + "id=" + id + ", nazwa=" + nazwa;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.id);
        hash = 89 * hash + Objects.hashCode(this.nazwa);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Przedmioty other = (Przedmioty) obj;
        if (!Objects.equals(this.nazwa, other.nazwa)) {
            return false;
        }
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }


}


