package pl.pcz.wimii.zpi.smartplan.entities;
// Generated 2015-12-07 21:04:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Przedmioty generated by hbm2java
 */
@Entity
@Table(name="przedmioty"
    ,catalog="smartplan"
)
public class Przedmioty  implements java.io.Serializable {


     private Integer id;
     private RokKierunek rokKierunek;
     private String nazwa;
     private Set<Zajecia> zajecias = new HashSet<>(0);

    public Przedmioty() {
    }

	
    public Przedmioty(RokKierunek rokKierunek, String nazwa) {
        this.rokKierunek = rokKierunek;
        this.nazwa = nazwa;
    }
    public Przedmioty(RokKierunek rokKierunek, String nazwa, Set<Zajecia> zajecias) {
       this.rokKierunek = rokKierunek;
       this.nazwa = nazwa;
       this.zajecias = zajecias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rok_kierunek_id", nullable=false)
    public RokKierunek getRokKierunek() {
        return this.rokKierunek;
    }
    
    public void setRokKierunek(RokKierunek rokKierunek) {
        this.rokKierunek = rokKierunek;
    }

    
    @Column(name="nazwa", nullable=false, length=45)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="przedmioty" )
    public Set<Zajecia> getZajecias() {
        return this.zajecias;
    }
    
    public void setZajecias(Set<Zajecia> zajecias) {
        this.zajecias = zajecias;
    }




}


