package pl.pcz.wimii.zpi.smartplan.entities;
// Generated 2015-12-07 21:04:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zjazdy generated by hbm2java
 */
@Entity
@Table(name="zjazdy"
    ,catalog="smartplan"
)
public class Zjazdy  implements java.io.Serializable {


     private Integer id;
     private Date data;
     private Set<Zajecia> zajecias = new HashSet<>(0);

    public Zjazdy() {
    }

    public Zjazdy(Date data, Set zajecias) {
       this.data = data;
       this.zajecias = zajecias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zjazdy")
    public Set<Zajecia> getZajecias() {
        return this.zajecias;
    }
    
    public void setZajecias(Set<Zajecia> zajecias) {
        this.zajecias = zajecias;
    }




}


